services:
  web:
    image: dispatcharr/dispatcharr:alpha-v1
    container_name: dispatcharr_web
    ports:
      - 9191:9191
    depends_on:
      - db
      - redis
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - POSTGRES_HOST=db
      - POSTGRES_DB=dispatcharr
      - POSTGRES_USER=dispatch
      - POSTGRES_PASSWORD=secret
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    image: dispatcharr/dispatcharr:alpha-v1
    container_name: dispatcharr_celery
    depends_on:
      - db
      - redis
    volumes:
      - ../:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=dispatcharr
      - POSTGRES_USER=dispatch
      - POSTGRES_PASSWORD=secret
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: >
      bash -c "
      cd /app &&
      celery -A dispatcharr worker -l info
      "

  db:
    image: postgres:14
    container_name: dispatcharr_db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=dispatcharr
      - POSTGRES_USER=dispatch
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: dispatcharr_redis

volumes:
  postgres_data:
